services:
  - type: web
    name: cartify-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    pythonVersion: "3.12"  # ensure 3.12 for psycopg2-binary compatibility
