"""Add description, category, brand to products

Revision ID: 538f40a41af6
Revises: 9288fbd5d6f6
Create Date: 2025-09-24 10:45:57.290923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '538f40a41af6'
down_revision = '9288fbd5d6f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('brand', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('brand')
        batch_op.drop_column('category')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
